#!/bin/sh

set -eu

curl \
  -o openssl.tar.gz \
  "https://www.openssl.org/source/openssl-${VERSION}.tar.gz"

curl \
  -o openssl.tar.gz.asc \
  "https://www.openssl.org/source/openssl-${VERSION}.tar.gz.asc"

gpg --import /opt/resource/blob/pgp/*.asc
gpg --verify openssl.tar.gz.asc openssl.tar.gz
