#!/bin/bash

set -eu

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

exec fly -t "$FLY_TARGET" set-pipeline \
  -p openvpn-bosh-release \
  -c ci/pipelines/main.yml \
  -l config/private.yml
