#!/bin/sh

set -e

curl \
  -s \
  http://www.oberhumer.com/opensource/lzo/download/ \
  | grep -E 'href="lzo-[^"]+.tar.gz"' \
  | sed -E 's/^.+href="lzo-([^"]+).tar.gz".+$/\1/' \
  | sort -rV \
  | head -n1
