#!/bin/sh

set -eu

curl \
  -o lzo.tar.gz \
  "https://www.oberhumer.com/opensource/lzo/download/lzo-${VERSION}.tar.gz"

curl \
  -s \
  https://www.oberhumer.com/opensource/lzo/ \
  | grep -E 'SHA1: ' \
  | sed -E 's/^.+SHA1:\s+([a-f0-9]{40}).+$/\1/' \
  | head -n1 \
  > lzo.tar.gz.sha256sum

echo "$( cat lzo.tar.gz.sha256sum ) lzo.tar.gz" | sha1sum -c
