#!/bin/bash

set -e

git ls-remote --tags https://github.com/OpenVPN/openvpn.git \
  | cut -f2 \
  | grep -Ev '\^{}' \
  | grep -E '^refs/tags/v.+$' \
  | sed -E 's/^refs\/tags\/v(.+)$/\1/' \
  | tr '_' '.' \
  | grep -E '^\d+\.\d+\.\d+$' \
  | gsort -rV \
  | head -n1
