#!/bin/sh

set -eu

curl \
  -o openvpn.tar.gz \
  "https://swupdate.openvpn.org/community/releases/openvpn-${VERSION}.tar.gz"

curl \
  -o openvpn.tar.gz.asc \
  "https://swupdate.openvpn.org/community/releases/openvpn-${VERSION}.tar.gz.asc"

gpg --import /opt/resource/blob/pgp/*.asc
gpg --verify openvpn.tar.gz.asc openvpn.tar.gz
